#!/bin/bash
#
# shellcheck disable=SC2034  # config not code
 
# MOUNT_POINT is where your external drive should be mounted. The script
#    assumes the duplicacy sub-dir will be in the root of that device.
# default: detect first user
MOUNT_POINT="/media/$(id -un 1000)/backup"

# disk UUID for external backup drive
# find with: lsblk -no UUID "$(findmnt -no SOURCE "$MOUNT_POINT")
DISK_UUID=""

SNAPSHOT_ID="$(hostname)-root" # snapshot-id to back up, in .duplicacy/preferences
REPO_ROOT=/                    # duplicacy root dir, contains .duplicacy

OFFSITE_STORAGE=""          # storage name in .duplicacy/preferences
OFFSITE_UPLOAD_THREADS=5    # ~1MB/s per thread

PRUNE_HOUR=0                # hour of the day to prune, assuming script runs once per hour
PRUNE_DOW=7                 # day of week to prune, 1 is Monday
PRUNE_DRY_RUN=""            # set to "true" for dry-run, empty to prune
PRUNE_THREADS="$(nproc)"    # number of threads to run for prune
# duplicacy help prune | grep keep
# -keep <n:m> [+]   keep 1 snapshot every n days for snapshots older than m days
PRUNE_POLICY=(-keep 0:360 -keep 30:180 -keep 7:30 -keep 1:3)

CHECK_THREADS="$(nproc)"    # number of threads to run check, default to number of processor cores
CHECK_HOUR=0                # hour of the day to run check
CHECK_DOM=1                 # Day Of Month to run check, avoid >28 or it won't run every month
CHECK_OFFSITE="false"       # run check on offsite storage?

LOCKDIR="/var/lock"         # base path for job locking
LOGDIR="/var/log/duplicacy" # base path for logging
BIN_PATH="/usr/local/bin"   # path to local binaries
CMD="$BIN_PATH/duplicacy"   # path to duplicacy binary
REPO="https://api.github.com/repos/gilbertchen/duplicacy/releases/latest"

DATE="$(date +%Y%m%d)"
LOG="$LOGDIR/${SNAPSHOT_ID}-${DATE}.log"
ERROR_LOG="$LOGDIR/${SNAPSHOT_ID}-${DATE}.error.log"

